name: Cloudflare Status Check
on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Cloudflare Status
        run: curl -s "medium.kashyapprojects.workers.dev" | grep -q "All Systems Operational" && echo "Cloudflare is UP" || echo "Cloudflare might be DOWN"
