name: Cloudflare Status Check

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual execution

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Cloudflare Status
        run: |
          if curl -s "medium.kashyapprojects.workers.dev" | grep -q "All Systems Operational"; then
            echo "Cloudflare is UP"
          else
            echo "Cloudflare might be DOWN"
          fi
